services:
  api:
    container_name: xai-api
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: xai-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api

  redis:
    image: redis:7
    container_name: xai-redis
